[package]
name = "meadow"
version = "0.1.0"
edition = "2024"

[dependencies]
ariadne = "0.6.0"
chumsky = { version = "0.13.0", features = ["pratt"] }
clap = { version = "4.6.1", features = ["cargo", "derive"] }
env = "1.0.1"
env_logger = "0.11.10"
insta = "1.47.2"
itertools = "0.14.0"
lasso = { version = "0.7.3", features = ["multi-threaded"] }
log = "0.4.29"
logos = "0.16.1"
once_cell = "1.21.4"
rustyline = { version = "18.0.0", features = ["with-file-history", "derive"] }
