cabal-version: 3.0
name: meadow
version: 0.1.0.0
synopsis: The official compiler for the Meadow programming language
license: BSD-3-Clause
license-file: LICENSE
author: Chris McDearman
maintainer: mcdearmanchris@gmail.com
category: Language
build-type: Simple
extra-doc-files: CHANGELOG.md

common warnings
  ghc-options:
    -Wall
    -Werror=missing-signatures
    -Werror=incomplete-patterns
    -Werror=incomplete-uni-patterns
    -Wno-unused-do-bind

  default-extensions:
    FunctionalDependencies
    MagicHash
    MultiWayIf
    MultilineStrings
    OrPatterns
    OverloadedStrings
    PatternSynonyms
    RecordWildCards
    RequiredTypeArguments
    ScopedTypeVariables
    StrictData
    TypeFamilies
    ViewPatterns

  build-depends:
    array,
    base,
    bytestring,
    containers,
    diagnose,
    hashable,
    megaparsec,
    mtl,
    parser-combinators,
    pretty-simple,
    prettyprinter,
    primitive,
    stm,
    text,
    transformers,
    unordered-containers,
    vector,
    wcwidth,

executable mdwc
  import: warnings
  main-is: Main.hs
  build-depends: meadow
  hs-source-dirs: src
  default-language: GHC2024

library
  import: warnings
  build-depends: megaparsec
  exposed-modules:
    Meadow.AST
    Meadow.Lexer
    Meadow.Parser
    Meadow.Token
    Meadow.Utils

  hs-source-dirs: src
  default-language: GHC2024

test-suite tests
  import: warnings
  type: exitcode-stdio-1.0
  main-is: Spec.hs
  other-modules:
    Idyllic.LayoutSpec

  build-depends:
    -- hspec-golden-diff,
    hspec,
    hspec-discover,
    hspec-golden,

  build-tool-depends:
    hspec-discover:hspec-discover

  hs-source-dirs: compiler/tests
  default-language: GHC2024