[workspace]
resolver = "2"
members = ["meadow", "meadow-fmt", "meadow-lsp"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
meadow-fmt = { path = "meadow-fmt" }
meadow-lsp = { path = "meadow-lsp" }
meadow = { path = "meadow" }
meadow-compiler = { path = "../compiler/meadow-compiler" }
meadow-eval = { path = "../eval" }
