[workspace]
resolver = "2"
members = ["meadow-*"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
meadow-intern = { path = "meadow-intern" }
meadow-span = { path = "meadow-span" }
meadow-source = { path = "meadow-source" }
meadow-diagnostics = { path = "meadow-diagnostics" }
meadow-ast = { path = "meadow-ast" }
meadow-lexer = { path = "meadow-lexer" }
meadow-parser = { path = "meadow-parser" }
meadow-hir = { path = "meadow-hir" }
meadow-rename = { path = "meadow-rename" }
meadow-infer = { path = "meadow-infer" }
meadow-exhaust = { path = "meadow-exhaust" }
meadow-scc = { path = "meadow-scc" }
meadow-seq = { path = "meadow-seq" }
meadow-bytecode = { path = "meadow-bytecode" }
meadow-codegen = { path = "meadow-codegen" }
meadow-core = { path = "meadow-core" }
num-bigint = "0.4"
num-traits = "0.2"
ariadne = "0.6.0"
chumsky = { version = "0.13.0", features = ["pratt"] }
itertools = "0.14.0"
lasso = { version = "0.7.3", features = ["multi-threaded"] }
logos = "0.16.1"
once_cell = "1.21.4"
