[package]
name = "meadow-lexer"
version.workspace = true
edition.workspace = true

[lib]
name = "meadow_lexer"
path = "src/lib.rs"

[dependencies]
num-bigint.workspace = true
num-traits.workspace = true
meadow-intern.workspace = true
meadow-source.workspace = true
meadow-span.workspace = true
meadow-diagnostics.workspace = true
logos.workspace = true
